#pragma once

#include "CoreTypes.h"
#include "Modules/ModuleInterface.h"

/** One entry of the statically linked module table generated by LeonBuildTool. */
struct CORE_API FStaticallyLinkedModuleInfo
{
	const char* Name;
	IModuleInterface* (*InitializeModule)();
};

/**
 * Implemented by each executable's generated <Target>.ModuleInit.gen.cpp: every module linked into
 * the target that uses IMPLEMENT_MODULE, in dependency order (UBT: statically linked module list).
 */
const FStaticallyLinkedModuleInfo* GetStaticallyLinkedModules(int32& OutCount);

/** Name of the project's primary game module, or nullptr for engine targets (generated). */
extern const char* GPrimaryGameModuleName;

/** Owns module instances and their startup/shutdown (UE: FModuleManager, monolithic builds only). */
class CORE_API FModuleManager
{
public:
	static FModuleManager& Get();

	/** Creates and starts every statically linked module in dependency order. */
	void StartupStaticallyLinkedModules();

	/** Shuts down and destroys every module in reverse order. */
	void ShutdownModules();

	bool IsModuleLoaded(const char* ModuleName) const;
	IModuleInterface* GetModule(const char* ModuleName) const;

	int32 GetModuleCount() const;
	const char* GetModuleName(int32 Index) const;

private:
	struct FModuleEntry
	{
		const char* Name = nullptr;
		IModuleInterface* Module = nullptr;
	};

	FModuleEntry* Modules = nullptr;
	int32 NumModules = 0;
};

/** Default implementation for modules without startup logic. */
class CORE_API FDefaultModuleImpl : public IModuleInterface
{
};

/** Default implementation for game modules without startup logic. */
class CORE_API FDefaultGameModuleImpl : public FDefaultModuleImpl
{
public:
	virtual bool IsGameModule() const override
	{
		return true;
	}
};

/**
 * Registers a module: LeonBuildTool's generated module table calls InitializeModule_<ModuleName>.
 * A module listed in the table without this macro fails to link, which enforces it.
 */
#define IMPLEMENT_MODULE(ModuleImplClass, ModuleName)                                                                  \
	extern "C" IModuleInterface* InitializeModule_##ModuleName()                                                       \
	{                                                                                                                  \
		return new ModuleImplClass();                                                                                  \
	}

#define IMPLEMENT_GAME_MODULE(ModuleImplClass, ModuleName) IMPLEMENT_MODULE(ModuleImplClass, ModuleName)

/** The project's main game module; the game name comes from the .leonproject (LEON_PROJECT_NAME). */
#define IMPLEMENT_PRIMARY_GAME_MODULE(ModuleImplClass, ModuleName, GameName)                                           \
	IMPLEMENT_GAME_MODULE(ModuleImplClass, ModuleName)
