#pragma once

#include "CoreTypes.h"
#include "Modules/ModuleInterface.h"

/** One entry of the statically linked module table generated by LeonBuildTool. */
struct CORE_API FStaticallyLinkedModuleInfo
{
	const char* Name;
	IModuleInterface* (*InitializeModule)();
	/**
	 * Registers the module's reflected classes, structs and enums (RegisterReflection_<Module>, written by
	 * LeonHeaderTool in <Module>.init.gen.cpp), or nullptr for a module without reflected types. Referencing it from
	 * the table keeps static linking from dropping the registration. FModuleManager calls it right after creating the
	 * module, before OnProcessLoadedObjectsCallback and StartupModule.
	 */
	void (*RegisterReflection)();
};

/**
 * Implemented by each executable's generated <Target>.ModuleInit.gen.cpp: every module linked into
 * the target that uses IMPLEMENT_MODULE, in dependency order (UBT: statically linked module list).
 */
const FStaticallyLinkedModuleInfo* GetStaticallyLinkedModules(int32& OutCount);

/** Name of the project's primary game module, or nullptr for engine targets (generated). */
extern const char* GPrimaryGameModuleName;

/** Owns module instances and their startup/shutdown (UE: FModuleManager, monolithic builds only). */
class CORE_API FModuleManager
{
public:
	static FModuleManager& Get();

	/**
	 * Creates and starts every statically linked module in dependency order. For each module: InitializeModule, its
	 * RegisterReflection (records its reflected types), OnProcessLoadedObjectsCallback, then StartupModule.
	 */
	void StartupStaticallyLinkedModules();

	/**
	 * Called after each module is created and its reflected types recorded, before its StartupModule, with the module
	 * name and whether the new objects can be processed now (always true for statically linked modules). CoreUObject
	 * sets it to construct the recorded types (UE: FModuleManager::OnProcessLoadedObjectsCallback, which runs
	 * ProcessNewlyLoadedUObjects); Core never depends on CoreUObject. UE's is a multicast event; Leon's has a single
	 * listener, CoreUObject, so it is a function pointer and targets without CoreUObject pay almost nothing for it.
	 */
	typedef void (*FProcessLoadedObjectsCallback)(const TCHAR* ModuleName, bool bCanProcessNewlyLoadedObjects);
	FProcessLoadedObjectsCallback& OnProcessLoadedObjectsCallback()
	{
		return ProcessLoadedObjectsCallback;
	}

	/** Shuts down and destroys every module in reverse order. */
	void ShutdownModules();

	bool IsModuleLoaded(const char* ModuleName) const;
	IModuleInterface* GetModule(const char* ModuleName) const;

	int32 GetModuleCount() const;
	const char* GetModuleName(int32 Index) const;

private:
	struct FModuleEntry
	{
		const char* Name = nullptr;
		IModuleInterface* Module = nullptr;
	};

	FModuleEntry* Modules = nullptr;
	int32 NumModules = 0;
	FProcessLoadedObjectsCallback ProcessLoadedObjectsCallback = nullptr;
};

/** Default implementation for modules without startup logic. */
class CORE_API FDefaultModuleImpl : public IModuleInterface
{
};

/** Default implementation for game modules without startup logic. */
class CORE_API FDefaultGameModuleImpl : public FDefaultModuleImpl
{
public:
	virtual bool IsGameModule() const override
	{
		return true;
	}
};

/**
 * Registers a module: LeonBuildTool's generated module table calls InitializeModule_<ModuleName>.
 * A module listed in the table without this macro fails to link, which enforces it.
 */
#define IMPLEMENT_MODULE(ModuleImplClass, ModuleName)                                                                  \
	extern "C" IModuleInterface* InitializeModule_##ModuleName()                                                       \
	{                                                                                                                  \
		return new ModuleImplClass();                                                                                  \
	}

#define IMPLEMENT_GAME_MODULE(ModuleImplClass, ModuleName) IMPLEMENT_MODULE(ModuleImplClass, ModuleName)

/** The project's main game module; the game name comes from the .lproj (LEON_PROJECT_NAME). */
#define IMPLEMENT_PRIMARY_GAME_MODULE(ModuleImplClass, ModuleName, GameName)                                           \
	IMPLEMENT_GAME_MODULE(ModuleImplClass, ModuleName)
