#include "EngineLogs.h"

DEFINE_LOG_CATEGORY(LogEngine);
DEFINE_LOG_CATEGORY(LogLevel);
DEFINE_LOG_CATEGORY(LogPath);
DEFINE_LOG_CATEGORY(LogPhysics);
DEFINE_LOG_CATEGORY(LogSpawn);
DEFINE_LOG_CATEGORY(LogWorld);
