#pragma once

// All of Core math (UE: Math/UnrealMath.h). CoreMinimal.h includes this.

#include "Math/Axis.h"
#include "Math/Box.h"
#include "Math/Box2D.h"
#include "Math/BoxSphereBounds.h"
#include "Math/Color.h"
#include "Math/IntPoint.h"
#include "Math/IntVector.h"
#include "Math/InverseRotationMatrix.h"
#include "Math/MathFwd.h"
#include "Math/Matrix.h"
#include "Math/NumericLimits.h"
#include "Math/OrthoMatrix.h"
#include "Math/PerspectiveMatrix.h"
#include "Math/Plane.h"
#include "Math/Quat.h"
#include "Math/QuatRotationTranslationMatrix.h"
#include "Math/RandomStream.h"
#include "Math/RotationAboutPointMatrix.h"
#include "Math/RotationMatrix.h"
#include "Math/RotationTranslationMatrix.h"
#include "Math/Rotator.h"
#include "Math/ScaleMatrix.h"
#include "Math/ScaleRotationTranslationMatrix.h"
#include "Math/Sphere.h"
#include "Math/Transform.h"
#include "Math/TranslationMatrix.h"
#include "Math/UnrealMathUtility.h"
#include "Math/Vector.h"
#include "Math/Vector2D.h"
#include "Math/Vector4.h"
