#include "Commandlets/EmbedFontCommandlet.h"

#include "Factories/TrueTypeFontFactory.h"
#include "GSTextureLayout.h"
#include "LeonEdLog.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"

namespace
{

	/** The debug font's sizes in pixels, in EGSDebugFont's order (Tiny, Small), as the engine's UFonts of those names.
	 */
	constexpr int32 PixelHeights[] = {10, 14};
	/** Each size is one PSMT4 page of the GS (128 x 128 texels, 32 blocks) at most. */
	constexpr int32 PageSize = 128;
	/** The coverage levels: PSMT4's 16 CLUT entries. */
	constexpr int32 CoverageLevels = 16;
	/** Bytes a line of the generated arrays. */
	constexpr int32 BytesPerLine = 16;
	constexpr int32 PairsPerLine = 6;

	/** Appends Bytes as the body of a C array, BytesPerLine a line, indented by a tab. */
	void AppendBytes(FString& Out, const TArray<uint8>& Bytes)
	{
		for (int32 Index = 0; Index < Bytes.Num(); ++Index)
		{
			if (Index % BytesPerLine == 0)
			{
				Out += TEXT("\t");
			}
			Out += FString::Printf("0x%02x,", uint32(Bytes[Index]));
			const bool bLineEnd = (Index % BytesPerLine) == BytesPerLine - 1 || Index == Bytes.Num() - 1;
			Out += bLineEnd ? TEXT("\n") : TEXT(" ");
		}
	}

	/**
	 * A code point as a comment names it: U+XXXX and the character when it is printable ASCII (not the backslash, which
	 * would continue the line comment onto the next line).
	 */
	FString DescribeCodePoint(int32 CodePoint)
	{
		FString Out = FString::Printf("U+%04X", CodePoint);
		if (CodePoint > 0x20 && CodePoint < 0x7f && CodePoint != '\\')
		{
			Out += TEXT(" ");
			Out.AppendChar(TCHAR(CodePoint));
		}
		return Out;
	}

} // namespace

UEmbedFontCommandlet::UEmbedFontCommandlet(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	HelpDescription = TEXT("Writes the GS debug font compiled into GSCore from the engine's TrueType font");
	HelpUsage = TEXT("-run=EmbedFont [-check] [-source=<file.ttf>] [-output=<file.inl>]");
	LogToConsole = 1;
}

FString UEmbedFontCommandlet::GetDefaultSourcePath()
{
	return FPaths::ConvertRelativePathToFull(
		FPaths::EngineDir() + TEXT("SourceArt/EngineFonts/DejaVuSansCondensed.ttf"));
}

FString UEmbedFontCommandlet::GetDefaultOutputPath()
{
	return FPaths::ConvertRelativePathToFull(
		FPaths::EngineSourceDir() + TEXT("Runtime/GSCore/Private/GSDebugFontData.inl"));
}

bool UEmbedFontCommandlet::GenerateSource(const TArray<uint8>& TrueTypeFile, FString& OutSource, FString& OutError)
{
	OutSource.Reset();
	constexpr int32 NumSizes = UE_ARRAY_COUNT(PixelHeights);
	FRasterizedFont Fonts[NumSizes];
	for (int32 Size = 0; Size < NumSizes; ++Size)
	{
		// The importer of the game's fonts, so the debug text's glyphs are the HUD's.
		UTrueTypeFontFactory* Factory = NewObject<UTrueTypeFontFactory>();
		Factory->Height = PixelHeights[Size];
		Factory->TexturePageWidth = PageSize;
		Factory->TexturePageMaxHeight = PageSize;
		if (!Factory->RasterizeFont(TrueTypeFile.GetData(), TrueTypeFile.Num(), Fonts[Size], OutError))
		{
			return false;
		}
		if (Fonts[Size].Pages.Num() != 1)
		{
			OutError = FString::Printf(
				"the %d-pixel glyphs do not fit one %dx%d page", PixelHeights[Size], PageSize, PageSize);
			return false;
		}
	}

	// The local memory from the font's first block (a page boundary): each page at its alignment, then the CLUT.
	uint32 PageBlocks[NumSizes] = {};
	uint32 NextBlock = 0;
	for (int32 Size = 0; Size < NumSizes; ++Size)
	{
		const FRasterizedFont::FPage& Page = Fonts[Size].Pages[0];
		const uint32 Alignment = FGSTextureLayout::GetBaseAlignment(EGSPixelFormat::PSMT4, Page.Width, Page.Height);
		PageBlocks[Size] = ((NextBlock + Alignment - 1) / Alignment) * Alignment;
		NextBlock = PageBlocks[Size] + FGSTextureLayout::GetNumBlocks(EGSPixelFormat::PSMT4, Page.Width, Page.Height);
	}
	const uint32 ClutBlock = NextBlock;
	const uint32 NumBlocks = ClutBlock + FGSTextureLayout::GetClutBlocks(EGSPixelFormat::PSMT4);

	// The CLUT: white, its alpha the coverage (the UFonts' own).
	TArray<uint32> Palette;
	for (int32 Level = 0; Level < CoverageLevels; ++Level)
	{
		Palette.Add(0x00ffffffu | (uint32((Level * 255) / (CoverageLevels - 1)) << 24));
	}
	TArray<uint8> ClutImage;
	uint16 ClutWidth = 0;
	uint16 ClutHeight = 0;
	FGSTextureLayout::MakeClutImage(Palette, ClutImage, ClutWidth, ClutHeight);

	FString& Out = OutSource;
	Out += TEXT("// clang-format off\n");
	Out += TEXT("// GSDebugFontData.inl: the GS debug font (FGSDebugDraw), generated by `LeonCook -run=EmbedFont`\n");
	Out += TEXT("// (UEmbedFontCommandlet) from Engine/SourceArt/EngineFonts/DejaVuSansCondensed.ttf with\n");
	Out += TEXT("// UTrueTypeFontFactory. Do not edit: regenerate it (Docs/TOOLS.md).\n");
	Out += TEXT("//\n");
	Out += TEXT(
		"// DejaVu Sans Condensed: Copyright (c) 2003 by Bitstream, Inc. All Rights Reserved. Bitstream Vera is a\n");
	Out += TEXT("// trademark of Bitstream, Inc. DejaVu changes are in the public domain. The license is\n");
	Out += TEXT("// Engine/SourceArt/EngineFonts/LICENSE.txt (Engine/SourceArt/LICENSES.md).\n");
	Out += TEXT("//\n");
	Out += TEXT(
		"// Included by GSDebugDraw.cpp, which defines FGSDebugGlyph, FGSDebugKerningPair and FGSDebugFontSize.\n");
	Out += TEXT("\n");
	Out += TEXT("namespace GSDebugFontData\n{\n\n");
	Out += TEXT(
		"/** The 64-word blocks the font takes in the GS's local memory from its first block (a page boundary). */\n");
	Out += FString::Printf("constexpr uint32 NumBlocks = %u;\n", NumBlocks);
	Out += TEXT("/** The CLUT's block from the font's first block. */\n");
	Out += FString::Printf("constexpr uint32 ClutBlock = %u;\n\n", ClutBlock);
	Out += FString::Printf("/** The CLUT every size shares: %d entries, white, the alpha the glyph's coverage (%u x %u "
						   "PSMCT32, CSM1). */\n",
		CoverageLevels, uint32(ClutWidth), uint32(ClutHeight));
	Out += FString::Printf("alignas(16) const uint8 Clut[%d] = {\n", ClutImage.Num());
	AppendBytes(Out, ClutImage);
	Out += TEXT("};\n");

	for (int32 Size = 0; Size < NumSizes; ++Size)
	{
		const FRasterizedFont& Font = Fonts[Size];
		const FRasterizedFont::FPage& Page = Font.Pages[0];
		const int32 Height = PixelHeights[Size];

		// PSMT4 as the GS takes it (manual 4.3): rows top first, the first texel of a byte in its low nibble.
		TArray<uint8> Texels;
		Texels.SetNumZeroed((Page.Width * Page.Height) / 2);
		for (int32 Texel = 0; Texel < Page.Width * Page.Height; ++Texel)
		{
			const uint8 Level = Page.Coverage[Texel];
			Texels[Texel / 2] |= uint8((Texel & 1) != 0 ? Level << 4 : Level);
		}
		Out += FString::Printf(
			"\n/** %d pixels: a %d x %d PSMT4 page, rows top first, a byte's first texel in its low nibble. */\n",
			Height, Page.Width, Page.Height);
		Out += FString::Printf("alignas(16) const uint8 Texels%d[%d] = {\n", Height, Texels.Num());
		AppendBytes(Out, Texels);
		Out += TEXT("};\n");

		Out += FString::Printf("\n/** %d pixels: each code point's glyph: U, V, width, height, left bearing, top "
							   "offset, advance (0: none). */\n",
			Height);
		Out += FString::Printf("const FGSDebugGlyph Glyphs%d[%d] = {\n", Height, Font.Characters.Num());
		for (int32 CodePoint = 0; CodePoint < Font.Characters.Num(); ++CodePoint)
		{
			const FFontCharacter& Character = Font.Characters[CodePoint];
			if (Character.USize > 255 || Character.VSize > 255 || Character.StartU > 255 || Character.StartV > 255 ||
				Character.Advance > 255 || Character.HorizontalOffset < -128 || Character.HorizontalOffset > 127 ||
				Character.VerticalOffset < -128 || Character.VerticalOffset > 127)
			{
				OutError = FString::Printf(
					"the %d-pixel glyph of %s is out of the table's range", Height, *DescribeCodePoint(CodePoint));
				return false;
			}
			Out += FString::Printf("\t{%d, %d, %d, %d, %d, %d, %d}, // %s\n", Character.StartU, Character.StartV,
				Character.USize, Character.VSize, Character.HorizontalOffset, Character.VerticalOffset,
				Character.Advance, *DescribeCodePoint(CodePoint));
		}
		Out += TEXT("};\n");

		const int32 NumPairs = Font.KerningPairs.Num();
		Out += FString::Printf("\n/** %d pixels: the kerning pairs, (first << 8) | second, sorted, and the pixels "
							   "added to the first's advance. */\n",
			Height);
		if (NumPairs > 0)
		{
			Out += FString::Printf("const FGSDebugKerningPair Kerning%d[%d] = {\n", Height, NumPairs);
			for (int32 Index = 0; Index < NumPairs; ++Index)
			{
				const FFontKerningPair& Pair = Font.KerningPairs[Index];
				const uint32 First = Pair.Pair >> 16;
				const uint32 Second = Pair.Pair & 0xffffu;
				if (First > 255 || Second > 255 || Pair.Amount < -128 || Pair.Amount > 127)
				{
					OutError = FString::Printf("a %d-pixel kerning pair is out of the table's range", Height);
					return false;
				}
				if (Index % PairsPerLine == 0)
				{
					Out += TEXT("\t");
				}
				Out += FString::Printf("{0x%04x, %d},", (First << 8) | Second, Pair.Amount);
				const bool bLineEnd = (Index % PairsPerLine) == PairsPerLine - 1 || Index == NumPairs - 1;
				Out += bLineEnd ? TEXT("\n") : TEXT(" ");
			}
			Out += TEXT("};\n");
		}
	}

	Out += TEXT("\n/** The sizes, in EGSDebugFont's order. */\n");
	Out += FString::Printf("const FGSDebugFontSize Sizes[%d] = {\n", NumSizes);
	for (int32 Size = 0; Size < NumSizes; ++Size)
	{
		const FRasterizedFont& Font = Fonts[Size];
		const FRasterizedFont::FPage& Page = Font.Pages[0];
		const int32 Height = PixelHeights[Size];
		const FString Kerning = Font.KerningPairs.Num() > 0
			? FString::Printf("Kerning%d, %d", Height, Font.KerningPairs.Num())
			: TEXT("nullptr, 0");
		Out += FString::Printf("\t{%d, %d, %d, %d, %d, %d, %d, %d, %u, %u, Texels%d, Glyphs%d, %s},\n", Height,
			FMath::RoundToInt(Font.Ascent), FMath::RoundToInt(Font.Descent), FMath::RoundToInt(Font.Leading),
			Page.Width, Page.Height, int32(FMath::FloorLog2(uint32(Page.Width))),
			int32(FMath::FloorLog2(uint32(Page.Height))),
			uint32(FGSTextureLayout::GetBufferWidth(EGSPixelFormat::PSMT4, uint32(Page.Width))), PageBlocks[Size],
			Height, Height, *Kerning);
	}
	Out += TEXT("};\n\n");
	Out += TEXT("} // namespace GSDebugFontData\n");
	Out += TEXT("// clang-format on\n");
	return true;
}

int32 UEmbedFontCommandlet::Main(const FString& Params)
{
	TArray<FString> Tokens;
	TArray<FString> Switches;
	TMap<FString, FString> ParamsMap;
	ParseCommandLine(*Params, Tokens, Switches, ParamsMap);
	const FString* SourceParam = ParamsMap.Find(TEXT("source"));
	const FString* OutputParam = ParamsMap.Find(TEXT("output"));
	const FString SourcePath =
		SourceParam != nullptr ? FPaths::ConvertRelativePathToFull(*SourceParam) : GetDefaultSourcePath();
	const FString OutputPath =
		OutputParam != nullptr ? FPaths::ConvertRelativePathToFull(*OutputParam) : GetDefaultOutputPath();
	const bool bCheck = Switches.Contains(TEXT("check"));

	TArray<uint8> TrueTypeFile;
	if (!FFileHelper::LoadFileToArray(TrueTypeFile, *SourcePath))
	{
		UE_LOG(LogLeonEd, Error, "EmbedFont: cannot read '%s'", *SourcePath);
		return 1;
	}
	FString Source;
	FString Error;
	if (!GenerateSource(TrueTypeFile, Source, Error))
	{
		UE_LOG(LogLeonEd, Error, "EmbedFont: '%s': %s", *SourcePath, *Error);
		return 1;
	}
	const TArrayView<const uint8> Bytes(reinterpret_cast<const uint8*>(*Source), Source.Len());
	if (bCheck)
	{
		TArray<uint8> Existing;
		if (!FFileHelper::LoadFileToArray(Existing, *OutputPath) || Existing.Num() != Bytes.Num() ||
			FMemory::Memcmp(Existing.GetData(), Bytes.GetData(), SIZE_T(Bytes.Num())) != 0)
		{
			UE_LOG(LogLeonEd, Error, "EmbedFont: '%s' is not what '%s' generates: run LeonCook -run=EmbedFont",
				*OutputPath, *SourcePath);
			return 1;
		}
		UE_LOG(LogLeonEd, Display, "EmbedFont: '%s' is up to date", *OutputPath);
		return 0;
	}
	if (!FFileHelper::SaveArrayToFile(Bytes, *OutputPath))
	{
		UE_LOG(LogLeonEd, Error, "EmbedFont: cannot write '%s'", *OutputPath);
		return 1;
	}
	UE_LOG(LogLeonEd, Display, "EmbedFont: wrote '%s' (%d bytes)", *OutputPath, Bytes.Num());
	return 0;
}
