# LeonBuildTool target instantiation (UnrealBuildTool: UEBuildTarget / UEBuildModuleCPP).
#
# For each target: resolve the module closure from its roots, instantiate each module once as a
# CMake library (Module.<Name> STATIC/INTERFACE, ThirdParty.<Name> for External), compile the launch
# module straight into the executable with the target's macros, generate the statically linked
# module table (<Target>.ModuleInit.gen.cpp) and optionally collect <Module>/Private/Tests/**.

function(leon_module_target_name Name OutVar)
	leon_module_get(${Name} TYPE Type)
	if(Type STREQUAL "External")
		set(${OutVar} "ThirdParty.${Name}" PARENT_SCOPE)
	else()
		set(${OutVar} "Module.${Name}" PARENT_SCOPE)
	endif()
endfunction()

function(_leon_module_ext_dirs Name OutVar)
	get_property(Dirs GLOBAL PROPERTY LEON_MODULE_EXT_${Name}_DIRS)
	set(${OutVar} "${Dirs}" PARENT_SCOPE)
endfunction()

# A module without Public/Private/Classes folders is "flat" (UE game-module style).
function(_leon_module_is_flat Name OutVar)
	leon_module_get(${Name} DIR Dir)
	if(IS_DIRECTORY "${Dir}/Public" OR IS_DIRECTORY "${Dir}/Private" OR IS_DIRECTORY "${Dir}/Classes")
		set(${OutVar} FALSE PARENT_SCOPE)
	else()
		set(${OutVar} TRUE PARENT_SCOPE)
	endif()
endfunction()

function(leon_module_include_dirs Name OutPublic OutPrivate)
	leon_module_get(${Name} DIR Dir)
	_leon_module_ext_dirs(${Name} ExtDirs)
	_leon_module_is_flat(${Name} Flat)
	set(Public)
	set(Private)
	if(Flat)
		list(APPEND Public "${Dir}")
	endif()
	foreach(Root IN ITEMS "${Dir}" LISTS ExtDirs)
		foreach(Sub Public Classes)
			if(IS_DIRECTORY "${Root}/${Sub}")
				list(APPEND Public "${Root}/${Sub}")
			endif()
		endforeach()
		if(IS_DIRECTORY "${Root}/Private")
			list(APPEND Private "${Root}/Private")
		endif()
	endforeach()
	leon_module_effective(${Name} PUBLIC_INCLUDE_PATHS Extra)
	foreach(Path IN LISTS Extra)
		if(NOT IS_ABSOLUTE "${Path}")
			set(Path "${Dir}/${Path}")
		endif()
		list(APPEND Public "${Path}")
	endforeach()
	leon_module_effective(${Name} PRIVATE_INCLUDE_PATHS Extra)
	foreach(Path IN LISTS Extra)
		if(NOT IS_ABSOLUTE "${Path}")
			set(Path "${Dir}/${Path}")
		endif()
		list(APPEND Private "${Path}")
	endforeach()
	set(${OutPublic} "${Public}" PARENT_SCOPE)
	set(${OutPrivate} "${Private}" PARENT_SCOPE)
endfunction()

# Drop files under folders named after a platform/group that does not apply (UBT folder rule).
function(_leon_filter_platform_folders Root InFiles OutVar)
	set(Kept)
	foreach(File IN LISTS InFiles)
		file(RELATIVE_PATH Rel "${Root}" "${File}")
		get_filename_component(RelDir "${Rel}" DIRECTORY)
		string(REPLACE "/" ";" Parts "${RelDir}")
		set(Skip FALSE)
		foreach(Part IN LISTS Parts)
			if(Part IN_LIST LEON_EXCLUDED_PLATFORM_FOLDERS)
				set(Skip TRUE)
				break()
			endif()
		endforeach()
		if(NOT Skip)
			list(APPEND Kept "${File}")
		endif()
	endforeach()
	set(${OutVar} "${Kept}" PARENT_SCOPE)
endfunction()

# Sources: Private/** (+ platform extension Private/**), minus Tests/, foreign platform folders and
# EXCLUDE_SOURCES. Flat modules use the whole module folder.
function(leon_module_sources Name OutVar)
	leon_module_get(${Name} DIR Dir)
	_leon_module_ext_dirs(${Name} ExtDirs)
	_leon_module_is_flat(${Name} Flat)
	set(Sources)
	set(Roots)
	if(Flat)
		list(APPEND Roots "${Dir}")
	elseif(IS_DIRECTORY "${Dir}/Private")
		list(APPEND Roots "${Dir}/Private")
	endif()
	foreach(ExtDir IN LISTS ExtDirs)
		if(IS_DIRECTORY "${ExtDir}/Private")
			list(APPEND Roots "${ExtDir}/Private")
		endif()
	endforeach()
	foreach(Root IN LISTS Roots)
		file(GLOB_RECURSE Found CONFIGURE_DEPENDS "${Root}/*.cpp" "${Root}/*.c")
		list(FILTER Found EXCLUDE REGEX "^${Root}/Tests/")
		_leon_filter_platform_folders("${Root}" "${Found}" Found)
		list(APPEND Sources ${Found})
	endforeach()
	leon_module_effective(${Name} EXCLUDE_SOURCES Excludes)
	foreach(Pattern IN LISTS Excludes)
		file(GLOB Excluded "${Dir}/${Pattern}")
		if(Excluded)
			list(REMOVE_ITEM Sources ${Excluded})
		endif()
	endforeach()
	set(${OutVar} "${Sources}" PARENT_SCOPE)
endfunction()

# Automation tests: <Module>/Private/Tests/** (flat modules: <Module>/Tests/**).
function(leon_module_test_sources Name OutVar)
	leon_module_get(${Name} DIR Dir)
	_leon_module_ext_dirs(${Name} ExtDirs)
	_leon_module_is_flat(${Name} Flat)
	set(Roots)
	if(Flat)
		list(APPEND Roots "${Dir}/Tests")
	else()
		list(APPEND Roots "${Dir}/Private/Tests")
	endif()
	foreach(ExtDir IN LISTS ExtDirs)
		list(APPEND Roots "${ExtDir}/Private/Tests")
	endforeach()
	set(Sources)
	foreach(Root IN LISTS Roots)
		if(IS_DIRECTORY "${Root}")
			file(GLOB_RECURSE Found CONFIGURE_DEPENDS "${Root}/*.cpp")
			_leon_filter_platform_folders("${Root}" "${Found}" Found)
			list(APPEND Sources ${Found})
		endif()
	endforeach()
	set(${OutVar} "${Sources}" PARENT_SCOPE)
endfunction()

function(leon_module_all_dependencies Name OutVar)
	leon_module_effective(${Name} PUBLIC_DEPENDENCIES Public)
	leon_module_effective(${Name} PRIVATE_DEPENDENCIES Private)
	leon_module_effective(${Name} CIRCULAR_DEPENDENCIES Circular)
	set(All ${Public} ${Private} ${Circular})
	list(REMOVE_DUPLICATES All)
	set(${OutVar} "${All}" PARENT_SCOPE)
endfunction()

function(_leon_require_module Name Context)
	leon_module_exists(${Name} Exists)
	if(NOT Exists)
		message(FATAL_ERROR "LeonBuildTool: unknown module '${Name}' (required by ${Context})")
	endif()
	leon_module_allowed(${Name} Allowed)
	if(NOT Allowed)
		message(FATAL_ERROR "LeonBuildTool: module '${Name}' is not available on ${LEON_PLATFORM} (required by ${Context})")
	endif()
endfunction()

# Breadth-first closure of the roots over public/private/circular dependencies.
function(leon_resolve_closure Context OutVar)
	set(Closure)
	set(Queue ${ARGN})
	while(Queue)
		list(POP_FRONT Queue Name)
		if(Name IN_LIST Closure)
			continue()
		endif()
		_leon_require_module(${Name} "${Context}")
		list(APPEND Closure ${Name})
		leon_module_all_dependencies(${Name} Deps)
		foreach(Dep IN LISTS Deps)
			if(NOT Dep IN_LIST Closure)
				_leon_require_module(${Dep} "module ${Name}")
				list(APPEND Queue ${Dep})
			endif()
		endforeach()
	endwhile()
	set(${OutVar} "${Closure}" PARENT_SCOPE)
endfunction()

# Dependency-first order (circular edges are ignored for ordering).
function(_leon_topo_visit Name)
	get_property(State GLOBAL PROPERTY _LEON_TOPO_${Name})
	if(State)
		return()
	endif()
	set_property(GLOBAL PROPERTY _LEON_TOPO_${Name} VISITING)
	leon_module_effective(${Name} PUBLIC_DEPENDENCIES Public)
	leon_module_effective(${Name} PRIVATE_DEPENDENCIES Private)
	foreach(Dep IN LISTS Public Private)
		_leon_topo_visit(${Dep})
	endforeach()
	set_property(GLOBAL PROPERTY _LEON_TOPO_${Name} DONE)
	set_property(GLOBAL APPEND PROPERTY _LEON_TOPO_ORDER ${Name})
endfunction()

function(leon_topological_order OutVar)
	set_property(GLOBAL PROPERTY _LEON_TOPO_ORDER "")
	foreach(Name IN LISTS ARGN)
		set_property(GLOBAL PROPERTY _LEON_TOPO_${Name} "")
	endforeach()
	foreach(Name IN LISTS ARGN)
		_leon_topo_visit(${Name})
	endforeach()
	get_property(Order GLOBAL PROPERTY _LEON_TOPO_ORDER)
	set(Result)
	foreach(Name IN LISTS Order)
		if(Name IN_LIST ARGN)
			list(APPEND Result ${Name})
		endif()
	endforeach()
	set(${OutVar} "${Result}" PARENT_SCOPE)
endfunction()

# Usage requirements shared by module libraries and the launch module compiled into an executable.
# Scope: PUBLIC/PRIVATE for a STATIC library, INTERFACE for a header-only one, PRIVATE for an exe.
function(_leon_apply_module_usage Target Name PublicScope PrivateScope)
	leon_module_include_dirs(${Name} PublicIncludes PrivateIncludes)
	target_include_directories(${Target} ${PublicScope} ${PublicIncludes})
	if(PrivateIncludes)
		target_include_directories(${Target} ${PrivateScope} ${PrivateIncludes})
	endif()

	string(TOUPPER "${Name}" NameUpper)
	target_compile_definitions(${Target} ${PublicScope} ${NameUpper}_API=)
	leon_module_effective(${Name} PUBLIC_DEFINITIONS PublicDefs)
	leon_module_effective(${Name} PRIVATE_DEFINITIONS PrivateDefs)
	if(PublicDefs)
		target_compile_definitions(${Target} ${PublicScope} ${PublicDefs})
	endif()
	if(PrivateDefs)
		target_compile_definitions(${Target} ${PrivateScope} ${PrivateDefs})
	endif()

	leon_module_effective(${Name} PUBLIC_DEPENDENCIES PublicDeps)
	leon_module_effective(${Name} PRIVATE_DEPENDENCIES PrivateDeps)
	leon_module_effective(${Name} CIRCULAR_DEPENDENCIES CircularDeps)
	# Circular dependencies (UE: CircularlyReferencedDependentModules) propagate like public ones:
	# their headers include each other.
	foreach(Dep IN LISTS PublicDeps CircularDeps)
		leon_module_target_name(${Dep} DepTarget)
		target_link_libraries(${Target} ${PublicScope} ${DepTarget})
	endforeach()
	foreach(Dep IN LISTS PrivateDeps)
		leon_module_target_name(${Dep} DepTarget)
		target_link_libraries(${Target} ${PrivateScope} ${DepTarget})
	endforeach()
	if(CircularDeps AND NOT PrivateScope STREQUAL "INTERFACE")
		set_target_properties(${Target} PROPERTIES LINK_INTERFACE_MULTIPLICITY 3)
	endif()

	leon_module_effective(${Name} PUBLIC_SYSTEM_LIBRARIES SystemLibs)
	if(SystemLibs)
		target_link_libraries(${Target} ${PublicScope} ${SystemLibs})
	endif()
	leon_module_effective(${Name} COMPILE_OPTIONS Options)
	if(Options AND NOT PrivateScope STREQUAL "INTERFACE")
		target_compile_options(${Target} ${PrivateScope} ${Options})
	endif()
endfunction()

function(leon_instantiate_module Name)
	get_property(Done GLOBAL PROPERTY LEON_MODULE_${Name}_INSTANTIATED)
	if(Done)
		return()
	endif()
	set_property(GLOBAL PROPERTY LEON_MODULE_${Name}_INSTANTIATED TRUE)

	leon_module_target_name(${Name} Target)
	leon_module_get(${Name} TYPE Type)
	leon_module_get(${Name} DIR LEON_MODULE_DIR)

	if(Type STREQUAL "External")
		leon_thirdparty_prepare(${Name} LEON_THIRDPARTY_DIR)
		if(COMMAND LeonExternal_${Name})
			cmake_language(CALL LeonExternal_${Name})
		endif()
		add_library(${Target} INTERFACE)
		leon_module_effective(${Name} EXTERNAL_TARGETS ExternalTargets)
		if(ExternalTargets)
			target_link_libraries(${Target} INTERFACE ${ExternalTargets})
		endif()
		leon_module_effective(${Name} PUBLIC_INCLUDE_PATHS Includes)
		foreach(Path IN LISTS Includes)
			if(NOT IS_ABSOLUTE "${Path}")
				set(Path "${LEON_THIRDPARTY_DIR}/${Path}")
			endif()
			target_include_directories(${Target} SYSTEM INTERFACE "${Path}")
		endforeach()
		leon_module_effective(${Name} PUBLIC_DEFINITIONS Defs)
		if(Defs)
			target_compile_definitions(${Target} INTERFACE ${Defs})
		endif()
		leon_module_effective(${Name} PUBLIC_DEPENDENCIES Deps)
		foreach(Dep IN LISTS Deps)
			leon_module_target_name(${Dep} DepTarget)
			target_link_libraries(${Target} INTERFACE ${DepTarget})
		endforeach()
		leon_module_effective(${Name} PUBLIC_SYSTEM_LIBRARIES SystemLibs)
		if(SystemLibs)
			target_link_libraries(${Target} INTERFACE ${SystemLibs})
		endif()
		return()
	endif()

	leon_module_sources(${Name} Sources)
	if(Sources)
		add_library(${Target} STATIC ${Sources})
		set_target_properties(${Target} PROPERTIES OUTPUT_NAME "${Name}")
		_leon_apply_module_usage(${Target} ${Name} PUBLIC PRIVATE)
		target_compile_definitions(${Target} PRIVATE LEON_MODULE_NAME="${Name}")
		leon_module_cxx_standard(${Name} Standard)
		leon_apply_compile_environment(${Target} ${Standard})
	else()
		add_library(${Target} INTERFACE)
		_leon_apply_module_usage(${Target} ${Name} INTERFACE INTERFACE)
	endif()
endfunction()

# Enabled plugins for a target (project/target settings over EnabledByDefault; Programs opt in).
function(_leon_enabled_plugins TargetName OutVar)
	get_property(Plugins GLOBAL PROPERTY LEON_PLUGINS)
	leon_target_get(${TargetName} TYPE Type)
	leon_target_get(${TargetName} ENABLE_PLUGINS TargetEnable)
	leon_target_get(${TargetName} DISABLE_PLUGINS TargetDisable)
	set(Enabled)
	foreach(Plugin IN LISTS Plugins)
		get_property(IsEnabled GLOBAL PROPERTY LEON_PLUGIN_${Plugin}_ENABLED_BY_DEFAULT)
		if(Type STREQUAL "Program")
			set(IsEnabled OFF)
		endif()
		if(Plugin IN_LIST LEON_PROJECT_ENABLED_PLUGINS)
			set(IsEnabled ON)
		endif()
		if(Plugin IN_LIST LEON_PROJECT_DISABLED_PLUGINS)
			set(IsEnabled OFF)
		endif()
		if(Plugin IN_LIST TargetEnable)
			set(IsEnabled ON)
		endif()
		if(Plugin IN_LIST TargetDisable)
			set(IsEnabled OFF)
		endif()
		if(IsEnabled)
			list(APPEND Enabled ${Plugin})
		endif()
	endforeach()
	set(${OutVar} "${Enabled}" PARENT_SCOPE)
endfunction()

function(_leon_plugin_root_modules TargetName OutVar)
	_leon_enabled_plugins(${TargetName} Plugins)
	leon_platform_names(${LEON_PLATFORM} PlatformNames)
	set(Roots)
	foreach(Plugin IN LISTS Plugins)
		get_property(Modules GLOBAL PROPERTY LEON_PLUGIN_${Plugin}_MODULES)
		foreach(Module IN LISTS Modules)
			get_property(AllowList GLOBAL PROPERTY LEON_PLUGIN_MODULE_${Module}_ALLOW_LIST)
			set(Allowed TRUE)
			if(AllowList)
				set(Allowed FALSE)
				foreach(Entry IN LISTS AllowList)
					if(Entry IN_LIST PlatformNames)
						set(Allowed TRUE)
					endif()
				endforeach()
			endif()
			if(Allowed)
				list(APPEND Roots ${Module})
			endif()
		endforeach()
	endforeach()
	set(${OutVar} "${Roots}" PARENT_SCOPE)
endfunction()

function(_leon_write_module_init File TargetName Modules PrimaryGameModule)
	set(Declarations "")
	set(Entries "")
	set(Count 0)
	foreach(Module IN LISTS Modules)
		string(APPEND Declarations "extern \"C\" IModuleInterface* InitializeModule_${Module}();\n")
		string(APPEND Entries "\t{ \"${Module}\", &InitializeModule_${Module} },\n")
		math(EXPR Count "${Count} + 1")
	endforeach()
	if(PrimaryGameModule)
		set(Primary "\"${PrimaryGameModule}\"")
	else()
		set(Primary "nullptr")
	endif()
	set(Content "// Generated by LeonBuildTool for target ${TargetName}. Do not edit.\n")
	string(APPEND Content "#include \"Modules/ModuleManager.h\"\n\n${Declarations}\n")
	if(Count GREATER 0)
		string(APPEND Content "static const FStaticallyLinkedModuleInfo GLeonStaticallyLinkedModules[] =\n{\n${Entries}};\n\n")
		string(APPEND Content "const FStaticallyLinkedModuleInfo* GetStaticallyLinkedModules(int32& OutCount)\n{\n\tOutCount = ${Count};\n\treturn GLeonStaticallyLinkedModules;\n}\n\n")
	else()
		string(APPEND Content "const FStaticallyLinkedModuleInfo* GetStaticallyLinkedModules(int32& OutCount)\n{\n\tOutCount = 0;\n\treturn nullptr;\n}\n\n")
	endif()
	string(APPEND Content "const char* GPrimaryGameModuleName = ${Primary};\n")
	file(WRITE "${File}.tmp" "${Content}")
	configure_file("${File}.tmp" "${File}" COPYONLY)
endfunction()

function(leon_build_target TargetName)
	leon_target_get(${TargetName} TYPE Type)
	leon_target_get(${TargetName} ORIGIN Origin)
	leon_target_get(${TargetName} LAUNCH_MODULE LaunchModule)
	leon_target_get(${TargetName} EXTRA_MODULE_NAMES ExtraModules)
	leon_target_get(${TargetName} COMPILE_AGAINST_ENGINE CompileAgainstEngine)
	leon_target_get(${TargetName} COLLECT_AUTOMATION_TESTS CollectTests)
	leon_target_get(${TargetName} OUTPUT_NAME OutputName)

	if(Type STREQUAL "Game" AND NOT ExtraModules)
		set(ExtraModules ${LEON_PROJECT_MODULES})
	endif()
	_leon_plugin_root_modules(${TargetName} PluginModules)
	set(Roots Core ${LaunchModule} ${ExtraModules} ${PluginModules})
	list(REMOVE_DUPLICATES Roots)
	leon_resolve_closure("target ${TargetName}" Closure ${Roots})

	# Every module except the launch module becomes a library.
	set(LibraryModules ${Closure})
	list(REMOVE_ITEM LibraryModules ${LaunchModule})
	foreach(Module IN LISTS LibraryModules)
		leon_instantiate_module(${Module})
	endforeach()

	# Statically linked module table (dependency order) + primary game module.
	leon_topological_order(Ordered ${Closure})
	set(Implemented)
	foreach(Module IN LISTS Ordered)
		leon_module_get(${Module} TYPE ModuleType)
		leon_module_get(${Module} NO_MODULE_IMPLEMENTATION NoImpl)
		if(ModuleType MATCHES "^(Runtime|Developer)$" AND NOT NoImpl)
			list(APPEND Implemented ${Module})
		endif()
	endforeach()
	set(PrimaryGameModule "")
	if(Type STREQUAL "Game")
		foreach(Module IN LISTS ExtraModules)
			leon_module_get(${Module} ORIGIN ModuleOrigin)
			if(ModuleOrigin STREQUAL "Project")
				set(PrimaryGameModule ${Module})
				break()
			endif()
		endforeach()
	endif()
	set(InitFile "${CMAKE_BINARY_DIR}/Generated/${TargetName}.ModuleInit.gen.cpp")
	_leon_write_module_init("${InitFile}" ${TargetName} "${Implemented}" "${PrimaryGameModule}")

	# Executable = launch module sources + module table (+ automation tests).
	leon_module_sources(${LaunchModule} LaunchSources)
	if(NOT LaunchSources)
		message(FATAL_ERROR "LeonBuildTool: launch module '${LaunchModule}' of target ${TargetName} has no sources")
	endif()
	set(TestSources)
	set(TestIncludes)
	if(CollectTests)
		foreach(Module IN LISTS Closure)
			leon_module_get(${Module} TYPE ModuleType)
			if(NOT ModuleType STREQUAL "External")
				leon_module_test_sources(${Module} ModuleTests)
				if(ModuleTests)
					list(APPEND TestSources ${ModuleTests})
					leon_module_include_dirs(${Module} Unused PrivateIncludes)
					list(APPEND TestIncludes ${PrivateIncludes})
				endif()
			endif()
		endforeach()
	endif()

	add_executable(${TargetName} ${LaunchSources} "${InitFile}" ${TestSources})
	_leon_apply_module_usage(${TargetName} ${LaunchModule} PRIVATE PRIVATE)
	foreach(Module IN LISTS LibraryModules)
		leon_module_target_name(${Module} ModuleTarget)
		target_link_libraries(${TargetName} PRIVATE ${ModuleTarget})
	endforeach()
	if(TestIncludes)
		list(REMOVE_DUPLICATES TestIncludes)
		target_include_directories(${TargetName} PRIVATE ${TestIncludes})
	endif()

	if(CompileAgainstEngine)
		set(WithEngine 1)
	else()
		set(WithEngine 0)
	endif()
	if(Type STREQUAL "Program")
		set(IsProgram 1)
	else()
		set(IsProgram 0)
	endif()
	if(CollectTests)
		set(WithTests 1)
	else()
		set(WithTests 0)
	endif()
	target_compile_definitions(${TargetName} PRIVATE
		WITH_ENGINE=${WithEngine}
		IS_PROGRAM=${IsProgram}
		WITH_DEV_AUTOMATION_TESTS=${WithTests}
		LEON_MODULE_NAME="${LaunchModule}"
		LEON_TARGET_NAME="${TargetName}"
		LEON_PROJECT_NAME="${LEON_PROJECT_NAME}"
		LEON_ROOT_DIR="${LEON_ROOT_DIR}")
	leon_platform_get(${LEON_PLATFORM} CXX_STANDARD Standard)
	leon_apply_compile_environment(${TargetName} ${Standard})

	# Output: <Project|Engine>/Binaries/<Platform>/<Target>[-<Platform>-<Config>]<suffix>
	if(Origin STREQUAL "Project")
		set(OutputDir "${LEON_PROJECT_DIR}/Binaries/${LEON_PLATFORM}")
	else()
		set(OutputDir "${LEON_ENGINE_DIR}/Binaries/${LEON_PLATFORM}")
	endif()
	if(NOT LEON_CONFIGURATION STREQUAL "Development")
		set(OutputName "${OutputName}-${LEON_PLATFORM}-${LEON_CONFIGURATION}")
	endif()
	leon_platform_get(${LEON_PLATFORM} EXECUTABLE_SUFFIX Suffix)
	set_target_properties(${TargetName} PROPERTIES
		RUNTIME_OUTPUT_DIRECTORY "${OutputDir}"
		OUTPUT_NAME "${OutputName}"
		SUFFIX "${Suffix}")
	message(STATUS "LeonBuildTool: ${TargetName} (${Type}, ${LEON_PLATFORM} ${LEON_CONFIGURATION}) modules: ${Closure}")
endfunction()
