// Hard-coded names registered first, in this order (UE: UObject/UnrealNames.inl). Each REGISTER_NAME(Index, Name)
// defines EName NAME_<Name> = Index; indices are contiguous. Append new names at the end.

REGISTER_NAME(0, None)

// Property types (reflection, CoreUObject).
REGISTER_NAME(1, ByteProperty)
REGISTER_NAME(2, IntProperty)
REGISTER_NAME(3, BoolProperty)
REGISTER_NAME(4, FloatProperty)
REGISTER_NAME(5, ObjectProperty)
REGISTER_NAME(6, NameProperty)
REGISTER_NAME(7, DelegateProperty)
REGISTER_NAME(8, DoubleProperty)
REGISTER_NAME(9, ArrayProperty)
REGISTER_NAME(10, StructProperty)
REGISTER_NAME(11, VectorProperty)
REGISTER_NAME(12, RotatorProperty)
REGISTER_NAME(13, StrProperty)
REGISTER_NAME(14, TextProperty)
REGISTER_NAME(15, InterfaceProperty)
REGISTER_NAME(16, MulticastDelegateProperty)
REGISTER_NAME(17, LazyObjectProperty)
REGISTER_NAME(18, SoftObjectProperty)
REGISTER_NAME(19, UInt64Property)
REGISTER_NAME(20, UInt32Property)
REGISTER_NAME(21, UInt16Property)
REGISTER_NAME(22, Int64Property)
REGISTER_NAME(23, Int16Property)
REGISTER_NAME(24, Int8Property)
REGISTER_NAME(25, MapProperty)
REGISTER_NAME(26, SetProperty)
REGISTER_NAME(27, EnumProperty)
REGISTER_NAME(28, ClassProperty)
REGISTER_NAME(29, SoftClassProperty)
REGISTER_NAME(30, WeakObjectProperty)

// Core structs / classes.
REGISTER_NAME(31, Core)
REGISTER_NAME(32, Engine)
REGISTER_NAME(33, Object)
REGISTER_NAME(34, Class)
REGISTER_NAME(35, Struct)
REGISTER_NAME(36, Enum)
REGISTER_NAME(37, Function)
REGISTER_NAME(38, Package)
REGISTER_NAME(39, Vector)
REGISTER_NAME(40, Vector2D)
REGISTER_NAME(41, Vector4)
REGISTER_NAME(42, Rotator)
REGISTER_NAME(43, Quat)
REGISTER_NAME(44, Transform)
REGISTER_NAME(45, Color)
REGISTER_NAME(46, LinearColor)
REGISTER_NAME(47, Guid)
REGISTER_NAME(48, Box)
REGISTER_NAME(49, Matrix)
REGISTER_NAME(50, Plane)
REGISTER_NAME(51, IntPoint)
REGISTER_NAME(52, IntVector)
REGISTER_NAME(53, SoftObjectPath)
REGISTER_NAME(54, SoftClassPath)

// Log categories and misc.
REGISTER_NAME(55, LogTemp)
REGISTER_NAME(56, Game)
REGISTER_NAME(57, Default)
REGISTER_NAME(58, Map)
REGISTER_NAME(59, Actor)
REGISTER_NAME(60, Root)
REGISTER_NAME(61, Script)
REGISTER_NAME(62, Error)
REGISTER_NAME(63, Warning)
REGISTER_NAME(64, Log)
REGISTER_NAME(65, Display)
