# LeonBuildTool command line (UnrealBuildTool.exe equivalent). Run in CMake script mode:
#
#   cmake -P LeonBuildTool.cmake -- <Target> <Platform> <Configuration> [options]
#   cmake -P LeonBuildTool.cmake -- -Mode=Setup
# (the -- keeps CMake from parsing our options: -Project= would otherwise read as -P roject=)
#
# Options:
#   -Project=<file.lproj>   build a game target of that project
#   -Mode=Build|Clean|Rebuild|GenerateClangDatabase|GenerateProjectFiles|Setup   (default Build)
#   -NoDocker                     never re-launch inside the platform's Docker image
#   -KeepGoing                    keep compiling after errors (ninja -k 0), to see every error at once
#
# Build trees: <Project>/Intermediate/Build/<Platform>/<Configuration> for games,
#              Engine/Intermediate/Build/<Platform>/<Configuration> for engine targets.
# Platforms with a DOCKER_IMAGE (PS2) re-run this script inside the container when their SDK
# environment variable (SDK_ENV, e.g. PS2DEV) is not set on the host.
cmake_minimum_required(VERSION 3.24)

get_filename_component(LEON_LBT_DIR "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)
get_filename_component(LEON_ENGINE_DIR "${LEON_LBT_DIR}/../../.." ABSOLUTE)
get_filename_component(LEON_ROOT_DIR "${LEON_ENGINE_DIR}/.." ABSOLUTE)

include("${LEON_LBT_DIR}/System/PlatformRegistry.cmake")
include("${LEON_LBT_DIR}/Configuration/ModuleRules.cmake")
include("${LEON_LBT_DIR}/System/ModuleDiscovery.cmake")
include("${LEON_LBT_DIR}/System/ThirdPartyDependencies.cmake")
leon_load_platforms("${LEON_ENGINE_DIR}")

# --- Arguments (everything after the script path) ---
set(_Args)
set(_AfterScript FALSE)
math(EXPR _LastArg "${CMAKE_ARGC} - 1")
foreach(_Index RANGE 1 ${_LastArg})
	set(_Arg "${CMAKE_ARGV${_Index}}")
	if(_AfterScript)
		list(APPEND _Args "${_Arg}")
	elseif(_Arg STREQUAL "-P")
		math(EXPR _ScriptIndex "${_Index} + 1")
		set(_SkipTo ${_ScriptIndex})
	elseif(DEFINED _SkipTo AND _Index EQUAL _SkipTo)
		set(_AfterScript TRUE)
	endif()
endforeach()

set(_Positional)
set(_ProjectFile "")
set(_Mode Build)
set(_NoDocker FALSE)
set(_KeepGoing FALSE)
foreach(_Arg IN LISTS _Args)
	if(_Arg STREQUAL "--")
		# Separator that stops CMake from parsing our options (e.g. -Project= would read as -P).
		continue()
	elseif(_Arg MATCHES "^-Project=(.+)$")
		set(_ProjectFile "${CMAKE_MATCH_1}")
		if(_ProjectFile MATCHES "\\.leonproject$")
			message(FATAL_ERROR "LeonBuildTool: .leonproject was renamed to .lproj (UE: .uproject); pass the .lproj file")
		endif()
	elseif(_Arg MATCHES "^-Mode=(.+)$")
		set(_Mode "${CMAKE_MATCH_1}")
	elseif(_Arg STREQUAL "-Clean")
		set(_Mode Clean)
	elseif(_Arg STREQUAL "-NoDocker")
		set(_NoDocker TRUE)
	elseif(_Arg STREQUAL "-KeepGoing")
		set(_KeepGoing TRUE)
	elseif(_Arg MATCHES "^-")
		message(FATAL_ERROR "LeonBuildTool: unknown option ${_Arg}")
	else()
		list(APPEND _Positional "${_Arg}")
	endif()
endforeach()

# --- Setup: download every pinned third-party dependency ---
if(_Mode STREQUAL "Setup")
	file(GLOB _ThirdPartyRoots LIST_DIRECTORIES TRUE
		"${LEON_ENGINE_DIR}/Source/ThirdParty"
		"${LEON_ENGINE_DIR}/Platforms/*/Source/ThirdParty")
	file(GLOB_RECURSE _PluginThirdParty LIST_DIRECTORIES TRUE "${LEON_ENGINE_DIR}/Plugins/*/ThirdParty")
	foreach(_Dir IN LISTS _PluginThirdParty)
		if(IS_DIRECTORY "${_Dir}" AND _Dir MATCHES "/Source/ThirdParty$")
			list(APPEND _ThirdPartyRoots "${_Dir}")
		endif()
	endforeach()
	foreach(_Root IN LISTS _ThirdPartyRoots)
		if(IS_DIRECTORY "${_Root}")
			leon_discover_modules("${_Root}" Engine)
		endif()
	endforeach()
	get_property(_Modules GLOBAL PROPERTY LEON_MODULES)
	foreach(_Module IN LISTS _Modules)
		leon_module_get(${_Module} DOWNLOAD_URL _Url)
		if(_Url)
			leon_thirdparty_prepare(${_Module} _Dir)
			message(STATUS "LeonBuildTool: ${_Module} ready (${_Dir})")
		endif()
	endforeach()
	return()
endif()

# --- GenerateProjectFiles: IDE solution for browsing / debugging (UE: GenerateProjectFiles.bat) ---
# Configures every Win64 engine target (plus the project's, with -Project=) with the host's default
# CMake generator (newest Visual Studio on Windows) into <Engine|Project>/Intermediate/ProjectFiles,
# and refreshes the root compile_commands.json for clangd from the Ninja tree.
if(_Mode STREQUAL "GenerateProjectFiles")
	if(_ProjectFile)
		get_filename_component(_ProjectFile "${_ProjectFile}" ABSOLUTE)
		get_filename_component(_ProjectDir "${_ProjectFile}" DIRECTORY)
		set(_ProjectFilesDir "${_ProjectDir}/Intermediate/ProjectFiles")
	else()
		set(_ProjectFilesDir "${LEON_ENGINE_DIR}/Intermediate/ProjectFiles")
	endif()
	if(CMAKE_HOST_WIN32)
		set(_HostPlatform Win64)
		set(_GeneratorArgs -A x64)
	else()
		set(_HostPlatform Linux)
		set(_GeneratorArgs)
	endif()
	set(_ConfigureArgs -S "${LEON_LBT_DIR}" -B "${_ProjectFilesDir}" ${_GeneratorArgs}
		"-DLEON_PLATFORM=${_HostPlatform}" "-DLEON_CONFIGURATION=Development")
	if(_ProjectFile)
		list(APPEND _ConfigureArgs "-DLEON_PROJECT_FILE=${_ProjectFile}")
	endif()
	execute_process(COMMAND "${CMAKE_COMMAND}" ${_ConfigureArgs} RESULT_VARIABLE _Result)
	if(NOT _Result EQUAL 0)
		message(FATAL_ERROR "LeonBuildTool: project file generation failed")
	endif()
	message(STATUS "LeonBuildTool: project files in ${_ProjectFilesDir}")
	return()
endif()

list(LENGTH _Positional _Count)
if(NOT _Count EQUAL 3)
	message(FATAL_ERROR "Usage: LeonBuildTool <Target> <Platform> <Configuration> [-Project=<file>] [-Mode=...]")
endif()
list(GET _Positional 0 _Target)
list(GET _Positional 1 _Platform)
list(GET _Positional 2 _Configuration)

get_property(_Platforms GLOBAL PROPERTY LEON_PLATFORMS)
if(NOT _Platform IN_LIST _Platforms)
	message(FATAL_ERROR "LeonBuildTool: unknown platform '${_Platform}' (known: ${_Platforms})")
endif()
if(NOT _Configuration MATCHES "^(Debug|Development|Shipping)$")
	message(FATAL_ERROR "LeonBuildTool: configuration must be Debug, Development or Shipping")
endif()
if(_ProjectFile)
	get_filename_component(_ProjectFile "${_ProjectFile}" ABSOLUTE)
	if(NOT EXISTS "${_ProjectFile}")
		message(FATAL_ERROR "LeonBuildTool: project file not found: ${_ProjectFile}")
	endif()
endif()

# --- Re-launch inside the platform's Docker image (PS2 on a host without ps2dev) ---
leon_platform_get(${_Platform} DOCKER_IMAGE _DockerImage)
leon_platform_get(${_Platform} DOCKER_ENTRY _DockerEntry)
leon_platform_get(${_Platform} SDK_ENV _SdkEnv)
set(_NeedDocker FALSE)
if(_DockerImage AND NOT _NoDocker)
	if(NOT _SdkEnv OR "$ENV{${_SdkEnv}}" STREQUAL "")
		set(_NeedDocker TRUE)
	endif()
endif()
if(_NeedDocker)
	set(_DockerArgs run --rm -v "${LEON_ROOT_DIR}:/leon" -w /leon)
	set(_ContainerProject "")
	if(_ProjectFile)
		file(RELATIVE_PATH _ProjectRel "${LEON_ROOT_DIR}" "${_ProjectFile}")
		if(_ProjectRel MATCHES "^\\.\\./" OR IS_ABSOLUTE "${_ProjectRel}")
			get_filename_component(_ProjectDir "${_ProjectFile}" DIRECTORY)
			get_filename_component(_ProjectName "${_ProjectFile}" NAME)
			list(APPEND _DockerArgs -v "${_ProjectDir}:/project")
			set(_ContainerProject "-Project=/project/${_ProjectName}")
		else()
			set(_ContainerProject "-Project=/leon/${_ProjectRel}")
		endif()
	endif()
	if(CMAKE_HOST_UNIX)
		execute_process(COMMAND id -u OUTPUT_VARIABLE _Uid OUTPUT_STRIP_TRAILING_WHITESPACE)
		execute_process(COMMAND id -g OUTPUT_VARIABLE _Gid OUTPUT_STRIP_TRAILING_WHITESPACE)
		list(APPEND _DockerArgs --user "${_Uid}:${_Gid}")
	endif()
	set(_Inner ${_Target} ${_Platform} ${_Configuration} -Mode=${_Mode} -NoDocker)
	if(_KeepGoing)
		list(APPEND _Inner -KeepGoing)
	endif()
	if(_ContainerProject)
		list(APPEND _Inner "${_ContainerProject}")
	endif()
	message(STATUS "LeonBuildTool: ${_Platform} build runs in Docker (${_DockerImage})")
	execute_process(COMMAND docker ${_DockerArgs} ${_DockerImage} sh "/leon/${_DockerEntry}" ${_Inner}
		RESULT_VARIABLE _Result)
	if(NOT _Result EQUAL 0)
		message(FATAL_ERROR "LeonBuildTool: Docker build failed (${_Result})")
	endif()
	return()
endif()

# --- Local build ---
if(_ProjectFile)
	get_filename_component(_ProjectDir "${_ProjectFile}" DIRECTORY)
	set(_BinaryDir "${_ProjectDir}/Intermediate/Build/${_Platform}/${_Configuration}")
else()
	set(_BinaryDir "${LEON_ENGINE_DIR}/Intermediate/Build/${_Platform}/${_Configuration}")
endif()

if(_Mode STREQUAL "Clean" OR _Mode STREQUAL "Rebuild")
	message(STATUS "LeonBuildTool: removing ${_BinaryDir}")
	file(REMOVE_RECURSE "${_BinaryDir}")
	if(_Mode STREQUAL "Clean")
		return()
	endif()
endif()

# Ninja reads MSVC's /showIncludes lines to track header dependencies. cl.exe prints them in its UI language (e.g.
# "Nota: inclusión del archivo:") encoded in the console's output code page, while CMake writes the prefix it detected
# into the build files as UTF-8 (msvc_deps_prefix). Ninja compares bytes, so under any other code page (850, 1252...)
# a non-ASCII prefix never matches: no header is recorded and a later header edit rebuilds nothing. Configure and
# build with the console in UTF-8 and give the caller back its code page.
set(_LeonCodePage "")
# chcp.com reads its whole command line: a forward-slash path would parse as options.
file(TO_NATIVE_PATH "$ENV{SystemRoot}/System32/chcp.com" _LeonChcp)
if(CMAKE_HOST_WIN32 AND EXISTS "${_LeonChcp}")
	execute_process(COMMAND "${_LeonChcp}" OUTPUT_VARIABLE _ChcpOutput ERROR_QUIET RESULT_VARIABLE _ChcpResult)
	if(_ChcpResult EQUAL 0 AND _ChcpOutput MATCHES "([0-9]+)[^0-9]*$" AND NOT CMAKE_MATCH_1 STREQUAL "65001")
		set(_LeonCodePage "${CMAKE_MATCH_1}")
		execute_process(COMMAND "${_LeonChcp}" 65001 OUTPUT_QUIET ERROR_QUIET)
	endif()
endif()
macro(_leon_restore_code_page)
	if(_LeonCodePage)
		execute_process(COMMAND "${_LeonChcp}" ${_LeonCodePage} OUTPUT_QUIET ERROR_QUIET)
	endif()
endmacro()

leon_platform_get(${_Platform} BUILD_TYPE_${_Configuration} _BuildType)
if(NOT _BuildType)
	set(_BuildType Release)
endif()
set(_ConfigureArgs
	-S "${LEON_LBT_DIR}"
	-B "${_BinaryDir}"
	-G Ninja
	"-DLEON_PLATFORM=${_Platform}"
	"-DLEON_CONFIGURATION=${_Configuration}"
	"-DCMAKE_BUILD_TYPE=${_BuildType}")
if(_ProjectFile)
	list(APPEND _ConfigureArgs "-DLEON_PROJECT_FILE=${_ProjectFile}")
endif()

set(_Stamp "${_BinaryDir}/LeonBuildTool.args")
set(_NeedConfigure TRUE)
if(EXISTS "${_BinaryDir}/build.ninja" AND EXISTS "${_Stamp}")
	file(READ "${_Stamp}" _Previous)
	if(_Previous STREQUAL "${_ConfigureArgs}")
		set(_NeedConfigure FALSE)
	endif()
endif()
if(_NeedConfigure)
	execute_process(COMMAND "${CMAKE_COMMAND}" ${_ConfigureArgs} RESULT_VARIABLE _Result)
	if(NOT _Result EQUAL 0)
		_leon_restore_code_page()
		message(FATAL_ERROR "LeonBuildTool: configure failed")
	endif()
	file(WRITE "${_Stamp}" "${_ConfigureArgs}")
endif()

if(_Mode STREQUAL "GenerateClangDatabase")
	_leon_restore_code_page()
	configure_file("${_BinaryDir}/compile_commands.json" "${LEON_ROOT_DIR}/compile_commands.json" COPYONLY)
	message(STATUS "LeonBuildTool: wrote ${LEON_ROOT_DIR}/compile_commands.json")
	return()
endif()

set(_BuildToolArgs)
if(_KeepGoing)
	set(_BuildToolArgs -- -k 0)
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_BinaryDir}" --target "${_Target}" ${_BuildToolArgs} RESULT_VARIABLE _Result)
_leon_restore_code_page()
if(NOT _Result EQUAL 0)
	message(FATAL_ERROR "LeonBuildTool: build of ${_Target} failed")
endif()
